
## Files
TILES_PATH = "Tiles/"
SAVE_FOLDER = "Saved/"
BLANK_IMAGE_NAME = "White.jpg"

## Error Constants
BLANK_IMAGE = -1
INVALID = -1

## Map Constants
TILE_SIZE_IN_PNG_IN_PX = 48
MAX_MAP_SIDE_DIMENSION = 40
MIN_MAP_SIDE_DIMENSION = 1

## Dimensions/Data
X = 0
Y = 1
RGBA = 4
MAP_DIMENSION = 8
TILE_COLUMNS = 5

## Padding

PAD_PIXEL = 1
PAD_TINY = 5
PAD_SMALL = 10
PAD_MEDIUM = 20
PAD_BIG = 40
PAD_LARGE = 50
PAD_HUGE = 80

## Font Sizes
FONT_SMALL = 20
FONT_MEDIUM = 30
FONT_LARGE = 40
FONT_TITLE = 50

## Screen Sizes
WIDTH = 1600
HEIGHT = 900

BUTTON_BORDER_WIDTH = 8

SCREEN_HALF = 0.5
SCREEN_THIRD = 0.33
SCREEN_QUARTER = 0.25
SCREEN_FIFTH = 0.2
SCREEN_EIGHTH = 0.125
SCREEN_TENTH = 0.1
SCREEN_DIMENSION_INPUT_WIDTH = 0.05
SCREEN_DIMENSION_INPUT_HEIGHT = 0.04


